version: "3.1"
services:
    webserver:
      image: nginx-amplify
      volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf #overwrite nginx conf with an updated version
       - ./jekyll/_site:/var/www/html #mount the static site to the container where the conf expects it to be
       - ./projects/php/:/var/www/php #mount any php demos
      ports:
       - 7000:80 #listen on port 7000
      environment:
       - NGINX_HOST=localhost
       - NGINX_PORT=80
       - API_KEY= 'f5ccfc935329dacf2646c7f1d95d9d82'
       - AMPLIFY_IMAGENAME= 'apotts-me-router-dev'
      command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx-debug -g 'daemon off;'"

    #php-fpm:
    #  build: projects/php-fpm
    #  container_name: php-fpm
    #  working_dir: /application
    #  volumes:
    #    - ./projects/php:/application
    #    - ./projects/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    php:
        image: php:7-fpm
        volumes:
            - ./projects/php/:/php
            #- ./projects/php/:/var/www/html/php
            - ./projects/php/:/var/www/html

    #try out a generic php apache server
    #php:
    #    image: php:7.0-apache
    #    volumes:
    #    - ./projects/php/:/var/www/html/
    #    - ./projects/phpdemo/config/php.ini:/usr/local/etc/php/php.ini
    #    - ./projects/phpdemo/apache2.conf:/etc/apache2/apache2.conf