web:
  image: nginx-amplify
  volumes:
   - ./nginx.conf:/etc/nginx/nginx.conf #overwrite nginx conf with an updated version
   - ./jekyll/_site:/var/www #mount the static site to the container where the conf expects it to be
  ports:
   - "7000:80" #listen on port 7000
  environment:
   - NGINX_HOST=localhost
   - NGINX_PORT=80
   - API_KEY= 'f5ccfc935329dacf2646c7f1d95d9d82'
   - AMPLIFY_IMAGENAME= 'apotts-me-router-dev'
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx-debug -g 'daemon off;'"
